name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Python 3.11.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"
      - run: make install
      - run: make lint
      - run: make test
